openapi: 3.1.0
info:
  version: 1.0.0
  title: Travellers app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of travellers app
tags:
  - name: Travellers
    description: Operations about travellers.
  - name: Users
    description: Operations about users
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:4000
paths:
  /auth/register:
    post:
    $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post: 
    $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post: 
    $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh-session:
    post: 
    $ref: ../swagger/paths/auth/refresh/post.yaml
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /users/me:
    get:
      $ref: ../swagger/paths/users/getMeUser.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{userId}/get.yaml
    patch:
      $ref: ../swagger/paths/users/{userId}/patch.yaml
  /users/{userId}/avatar:
    patch:
      $ref: ../swagger/paths/users/{userId}/patchAvatar.yaml
  /stories:
    get:
      $ref: ../swagger/paths/stories/get.yaml
    post:
      $ref: ../swagger/paths/stories/post.yaml
  /stories/{storyId}:
    get:
      $ref: ../swagger/paths/stories/{storyId}/get.yaml
    patch:
      $ref: ../swagger/paths/stories/{storyId}/path.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

    cookieAuth:     
      type: apiKey
      in: cookie
      name: accessToken
      description: JWT access token stored in httpOnly cookie

    sessionAuth:     
      type: apiKey
      in: cookie
      name: sessionId
      description: Session identifier stored in httpOnly cookie

